apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product
  namespace: default
spec:
  interval: 1m
  releaseName: product
  chart:
    spec:
      chart: product
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system